[build-system]
requires = ["setuptools>=82.0.1", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0"

[project]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
name = "nomad-distribution"
description = "nomad distribution template"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = ["nomad-lab[infrastructure]==1.4.2"]

[project.urls]
repository = "https://github.com/timval-differ/nomad-demo"

[project.optional-dependencies]
# Add your plugins to the list below.
plugins = [
    "nomad-north-jupyter>=0.2.5",
    "pynxtools>=0.13.2",
    "pynxtools-apm==0.5.1",
    "pynxtools-ellips==0.1.2",
    "pynxtools-em==0.4.4",
    "pynxtools-igor==0.1.5",
    "pynxtools-mpes==0.2.7",
    "pynxtools-raman==0.1.2",
    "pynxtools-spm==0.2.4",
    "pynxtools-xps==0.6.1",
    "pynxtools-xrd==0.0.8",
    "nomad-material-processing>=1.0.0"
]
jupyter = ["jupyter-events"]
gpu-action = []
cpu-action = []

dev = ["nomad-lab[infrastructure, dev]==1.4.2"]

[tool.uv]
extra-index-url = [
  "https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple",
]
prerelease = "explicit"

[tool.setuptools.packages.find]
exclude = ["gui*", "docs*", "config*"]
